/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jku_ssw_prsw2_ue9_jni_AdvancedJNISorter */

#ifndef _Included_org_jku_ssw_prsw2_ue9_jni_AdvancedJNISorter
#define _Included_org_jku_ssw_prsw2_ue9_jni_AdvancedJNISorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jku_ssw_prsw2_ue9_jni_AdvancedJNISorter
 * Method:    sort
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_org_jku_ssw_prsw2_ue9_jni_AdvancedJNISorter_sort
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
