/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jku_ssw_prsw2_ue9_jni_JNISorter */

#ifndef _Included_org_jku_ssw_prsw2_ue9_jni_JNISorter
#define _Included_org_jku_ssw_prsw2_ue9_jni_JNISorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jku_ssw_prsw2_ue9_jni_JNISorter
 * Method:    sort
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_org_jku_ssw_prsw2_ue9_jni_JNISorter_sort
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
