## 11

a)
    Klassenmitten
    ```{r}
    c(
        (0 + 10) / 2,
        (10 + 20) / 2,
        (20 + 30) / 2,
        (30 + 50) / 2,
        (50 + 100) / 2
    )
    ```
    Klassenbreiten
    ```{r}
    c(
        (10 - 0),
        (20 - 10),
        (30 - 20),
        (50 - 30),
        (100 - 50)
    )
    ```
    Relative Klassenhäufigkeiten
    ```{r}
    absolute_occurences <- c(47996, 191492, 124498, 104428, 67988, 31125)
    total_occurences <- sum(absolute_occurences)

    absolute_occurences
    total_occurences

    absolute_occurences / total_occurences
    ```

b)
    Prozentsatz der Fälle < 30.000
    ```{r}
    sum(absolute_occurences[1:3]) / total_occurences
    ```

c)
    Prozentsatz der Faelle >= 10 000 und <= 30 000 (nicht exakt? nur < 30 000)
    ```{r}
    sum(absolute_occurences[2:3]) / total_occurences
    ```

d)
    Prozentsatz der Faelle > 30 000
    ```{r}
    sum(absolute_occurences[4:length(absolute_occurences)]) / total_occurences
    ```
    Sanity check
    ```{r}
    sum(absolute_occurences[4:length(absolute_occurences)]) / total_occurences +
        sum(absolute_occurences[1:3]) / total_occurences
    ```

## 12

Klassenbreiten sind 10, Klassengrenzen 
```
[125, 135), [135, 145), [145, 155), [155, 165), [165, 175), [175, 185), [185, 195)
```

## 13

```{r}
revenues <- c(
    2, 4, 6, 4, 7, 5, 7, 5, 3, 5, 8, 3, 10, 9, 4, 3, 7, 4, 6, 4)
total_revenue <- sum(revenues)

revenues
```

a)
    ```{r}
    table(revenues)

    round(table(revenues) / length(revenues), 2)
    ```

b)
    ```{r}
    barplot(table(revenues), main = "revenues", ylab = "frequency",
        xlab = "revenue in M EUR")

    plot(ecdf(revenues))
    ```

c)
    ```{r}
    hist(revenues, c(0, 1.5, 3.5, 5.5, 7.5, 9.5, 11.5))
    hist(revenues, c(0, 1.5, 3.5, 6.5, 10.5))
    ```

## 14

```{r}
heights <- c(67, 46, 42, 58, 83, 79, 58, 132, 132, 173, 149, 152, 149, 169,
    171, 186, 153, 197)
hist(heights, breaks = "Scott")
```

## 15

```{r}
households <- c(380131, 182838, 87444, 52033, 20235)
total_households <- sum(households)
```

a)
    ```{r}
    barplot(households / total_households, main = "households",
        ylab = "rel. frequency", xlab = "household size",
        name = c("1", "2", "3", "4", "5 or more"))
    ```

b)
    Hoechstens etwas mehr als ein Viertel der Bevoelkerung lebt allein. (Hoechstens weil "5 und mehr" = 5 angenommen ist.)
    ```{r}
    persons <- households * seq_along(households)
    barplot(persons / sum(persons), main = "persons per household size",
        ylab = "rel. frequency, persons", xlab = "household size",
        name = c("1", "2", "3", "4", "5 or more"))
    ```

## 16

## 17

```{r}
wrong_questions <- c(1, 2, 0, 2, 0, 0, 1, 2, 0, 0, 2, 1, 2, 2, 2, 1, 1,
    1, 1, 6, 0, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 3, 3)
```

a)
    ```{r}
    table(wrong_questions)
    round(table(wrong_questions) / sum(wrong_questions), 2)
    ```

b)
    ```{r}
    hist(wrong_questions)
    plot(ecdf(revenues))
    ```

## 18

```{r}
number_residences <- rep(1:3, c(800, 150, 50))
table(number_residences)
plot(ecdf(number_residences))
```

## 19

```{r}
xi <- 2:6
fa <- c(3, 6, 3, 2, 4)
fb <- c(4, 1, 5, 4, 6)
```

a)
    ```{r}
    (1 / sum(xi)) * sum(fa * xi)
    (1 / sum(xi)) * sum(fb * xi)
    ```

b) Kein Unterschied in diesem Fall weil Klassenmitten gegeben (?)
    ```{r}
    (1 / sum(xi)) * sum(fa * xi)
    (1 / sum(xi)) * sum(fb * xi)
    ```
