## 122

a)
    ```{r}
    P_t <- (1 / 8) * 0.35 + (1 / 80) * 0.65
    P_t
    ```

b)
    P(e | t) = (P(t | e) * P(e)) / P(t)

    ```{r}
    ((1 / 8) * 0.35) / P_t
    ```

## 123

```{r}
0.041 * 0.58 + 0.029 * 0.30 + 0.93 * 0.21
```

## 124

```
P(s | k) = 0.3
P(s) = 0.5
P(k) = 0.3 * 0.5 + 0.001 * 0.5 ("kostenlos" kommt in 30% der spam-mails (50%), und in 0.1% der nicht-spam-mails (50%) vor)

P(k | s) = P(s | k) * P(s) / P(k)
```

```{r}
(0.3 * 0.5) / (0.3 * 0.5 + 0.001 * 0.5)
```

## 125

```
P(a | f) = P(f | a) * P(a) / P(f)

P(f | a) = 1 / 20
P(a) = 0.2
P(f) = 0.2 * 1 / 20 + 0.45 * 1 / 10 + 0.35 * 1 / 10
```

```{r}
(1 / 20 * 0.2) / (0.2 * 1 / 20 + 0.45 * 1 / 10 + 0.35 * 1 / 10)
```

## 126

a)
    ```{r}
    dbinom(3, 6, 0.3)
    ```

b)
    Gegenwahrscheinlichkeit von gar kein Raucher.

    ```{r}
    1 - dbinom(0, 3, 0.7)
    ```

c)
    ```
    P(r | l) = P(l | r) * P(r) / P(l)

    P(l | r) = 150 / 1000
    P(r) = 0.3
    P(l) = 150 / 1000 * 0.3 + 21 / 1000 * 0.7
    ```

    ```{r}
    (150 / 1000 * 0.3) / (150 / 1000 * 0.3 + 21 / 1000 * 0.7)
    ```

## 127

a)
    ```
    P(x < 68640) = 0.07

    phi((68640 - 110000) / sigma) = 0.07
    (68640 - 110000) / sigma = -1.476
    ```
    sigma = `r (68640 - 110000) / -1.476`

    Standardabweichung 28021.68

b)
    1 - P(x < 160000)

    ```{r}
    ((160000 - 110000) / 28021.68)
    ```

    P(x < 160000) = 0.9625

    P(x > 160000) = `r 1 - 0.9625`

## 128

a)
    Standardnormalverteilung, keine Transformation notwendig; z = 0.5, D(0.5) = 0.3829

b)
    TODO

## 129

P(x < d) = 0.9

phi((d - 300) / sqrt(6900)) = 0.9

(d - 300) / sqrt(6900) = 1.282

d = `r 1.282 * sqrt(6900) + 300`

## 130

P(120 - d < X < 120 + d) = 0.9

z = (0.9 + 1) / 2 = `r (0.9 + 1) / 2`

d = 1.645 * 20 = `r 1.645 * 20`

P(`r 120 - 1.645 * 20` < X < `r 120 + 1.645 * 20`)

## 131

a)
    P(x < 1050) - P(x < 990)

    ```{r}
    mu <- 970
    sigma <- 60

    z1 <- (1050 - mu) / sigma
    z2 <- (990 - mu) / sigma
    z1
    z2

    p <- 0.9082 - 0.6293
    p
    ```

b)
    P(x < d) = 0.75

    phi((d - 970) / 60) = 0.75

    (d - 970) / 60 = 0.674

    d = `r 0.674 * 60 + 970`

c)
    P(970 - d < x < 970 + d) = 0.95

    z = (1 + 0.95) / 2 = `r (1 + 0.95) / 2`

    d = 1.881 * 60 = `r 1.881 * 60`

    P(`r 970 - 1.881 * 60` < x < `r 970 + 1.881 * 60`)

## 132

a)
    P(x < 236) = 0.1

    phi((236 - 246) / sigma) = 0.1

    (236 - 246) / sigma = -1.282

    sigma = `r -10 / -1.282`

    1 - P(x < 247)

    z = (247 - 246) / sigma = `r (247 - 246) / (-10 / -1.282)`

    1 - 0.5398 = `r 1 - 0.5398`

b)
    TODO

## 133

```{r}
pbinom(2, 100, 0.06)
```

## 134

```{r}
prop.test(x = 80, n = 100, conf.level = 0.95, correct = FALSE)

n <- 100
p <- 80 / 100

margin <- qnorm(0.95) * sqrt(p * (1 - p) / n)

low <- n * (p - margin)
high <- n * (p + margin)

low
high
```
