# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mymqttmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mymqttmessages.proto',
  package='mymqttmessages',
  syntax='proto3',
  serialized_pb=_b('\n\x14mymqttmessages.proto\x12\x0emymqttmessages\"\xcd\x01\n\tPBMessage\x12\x0e\n\x06source\x18\x01 \x01(\r\x12\x0e\n\x06target\x18\x02 \x01(\r\x12\x31\n\x06number\x18\x65 \x01(\x0b\x32\x1f.mymqttmessages.PBGenericNumberH\x00\x12-\n\x04text\x18\x66 \x01(\x0b\x32\x1d.mymqttmessages.PBGenericTextH\x00\x12\x33\n\nledControl\x18\xcb\x01 \x01(\x0b\x32\x1c.mymqttmessages.PBLedControlH\x00\x42\t\n\x07msgtype\"!\n\x0fPBGenericNumber\x12\x0e\n\x06number\x18\x01 \x01(\x12\"\x1d\n\rPBGenericText\x12\x0c\n\x04text\x18\x01 \x01(\t\"q\n\x0cPBLedControl\x12 \n\x03led\x18\x01 \x01(\x0e\x32\x13.mymqttmessages.Led\x12)\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x19.mymqttmessages.LedAction\x12\x14\n\x0ctoggleRateHz\x18\x03 \x01(\r*#\n\x03Led\x12\x07\n\x03RED\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*(\n\tLedAction\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\n\n\x06TOGGLE\x10\x02\x42\x37\n#at.jku.pervasive.eps.mymqttmessagesB\x10ProtobufMessagesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_LED = _descriptor.EnumDescriptor(
  name='Led',
  full_name='mymqttmessages.Led',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=464,
)
_sym_db.RegisterEnumDescriptor(_LED)

Led = enum_type_wrapper.EnumTypeWrapper(_LED)
_LEDACTION = _descriptor.EnumDescriptor(
  name='LedAction',
  full_name='mymqttmessages.LedAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOGGLE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=466,
  serialized_end=506,
)
_sym_db.RegisterEnumDescriptor(_LEDACTION)

LedAction = enum_type_wrapper.EnumTypeWrapper(_LEDACTION)
RED = 0
GREEN = 1
BLUE = 2
OFF = 0
ON = 1
TOGGLE = 2



_PBMESSAGE = _descriptor.Descriptor(
  name='PBMessage',
  full_name='mymqttmessages.PBMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='mymqttmessages.PBMessage.source', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='mymqttmessages.PBMessage.target', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='mymqttmessages.PBMessage.number', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='mymqttmessages.PBMessage.text', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ledControl', full_name='mymqttmessages.PBMessage.ledControl', index=4,
      number=203, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msgtype', full_name='mymqttmessages.PBMessage.msgtype',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=41,
  serialized_end=246,
)


_PBGENERICNUMBER = _descriptor.Descriptor(
  name='PBGenericNumber',
  full_name='mymqttmessages.PBGenericNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='mymqttmessages.PBGenericNumber.number', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=281,
)


_PBGENERICTEXT = _descriptor.Descriptor(
  name='PBGenericText',
  full_name='mymqttmessages.PBGenericText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='mymqttmessages.PBGenericText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=312,
)


_PBLEDCONTROL = _descriptor.Descriptor(
  name='PBLedControl',
  full_name='mymqttmessages.PBLedControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='led', full_name='mymqttmessages.PBLedControl.led', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='mymqttmessages.PBLedControl.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toggleRateHz', full_name='mymqttmessages.PBLedControl.toggleRateHz', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=427,
)

_PBMESSAGE.fields_by_name['number'].message_type = _PBGENERICNUMBER
_PBMESSAGE.fields_by_name['text'].message_type = _PBGENERICTEXT
_PBMESSAGE.fields_by_name['ledControl'].message_type = _PBLEDCONTROL
_PBMESSAGE.oneofs_by_name['msgtype'].fields.append(
  _PBMESSAGE.fields_by_name['number'])
_PBMESSAGE.fields_by_name['number'].containing_oneof = _PBMESSAGE.oneofs_by_name['msgtype']
_PBMESSAGE.oneofs_by_name['msgtype'].fields.append(
  _PBMESSAGE.fields_by_name['text'])
_PBMESSAGE.fields_by_name['text'].containing_oneof = _PBMESSAGE.oneofs_by_name['msgtype']
_PBMESSAGE.oneofs_by_name['msgtype'].fields.append(
  _PBMESSAGE.fields_by_name['ledControl'])
_PBMESSAGE.fields_by_name['ledControl'].containing_oneof = _PBMESSAGE.oneofs_by_name['msgtype']
_PBLEDCONTROL.fields_by_name['led'].enum_type = _LED
_PBLEDCONTROL.fields_by_name['action'].enum_type = _LEDACTION
DESCRIPTOR.message_types_by_name['PBMessage'] = _PBMESSAGE
DESCRIPTOR.message_types_by_name['PBGenericNumber'] = _PBGENERICNUMBER
DESCRIPTOR.message_types_by_name['PBGenericText'] = _PBGENERICTEXT
DESCRIPTOR.message_types_by_name['PBLedControl'] = _PBLEDCONTROL
DESCRIPTOR.enum_types_by_name['Led'] = _LED
DESCRIPTOR.enum_types_by_name['LedAction'] = _LEDACTION

PBMessage = _reflection.GeneratedProtocolMessageType('PBMessage', (_message.Message,), dict(
  DESCRIPTOR = _PBMESSAGE,
  __module__ = 'mymqttmessages_pb2'
  # @@protoc_insertion_point(class_scope:mymqttmessages.PBMessage)
  ))
_sym_db.RegisterMessage(PBMessage)

PBGenericNumber = _reflection.GeneratedProtocolMessageType('PBGenericNumber', (_message.Message,), dict(
  DESCRIPTOR = _PBGENERICNUMBER,
  __module__ = 'mymqttmessages_pb2'
  # @@protoc_insertion_point(class_scope:mymqttmessages.PBGenericNumber)
  ))
_sym_db.RegisterMessage(PBGenericNumber)

PBGenericText = _reflection.GeneratedProtocolMessageType('PBGenericText', (_message.Message,), dict(
  DESCRIPTOR = _PBGENERICTEXT,
  __module__ = 'mymqttmessages_pb2'
  # @@protoc_insertion_point(class_scope:mymqttmessages.PBGenericText)
  ))
_sym_db.RegisterMessage(PBGenericText)

PBLedControl = _reflection.GeneratedProtocolMessageType('PBLedControl', (_message.Message,), dict(
  DESCRIPTOR = _PBLEDCONTROL,
  __module__ = 'mymqttmessages_pb2'
  # @@protoc_insertion_point(class_scope:mymqttmessages.PBLedControl)
  ))
_sym_db.RegisterMessage(PBLedControl)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#at.jku.pervasive.eps.mymqttmessagesB\020ProtobufMessages'))
# @@protoc_insertion_point(module_scope)
