```{r}
varp <- function(x) {var(x)*(length(x)-1)/length(x)}
sdp <- function(x) {sqrt(var(x)*(length(x)-1)/length(x))}
covp <- function(x,y) {cov(x,y)*(length(x)-1)/length(x)} 
```

## 59

a)
    ```{r}
    choose(13, 1) * choose(4, 2) * choose(12, 3) * choose(4, 1)^3
    ```

b)
    ```{r}
    choose(13, 2) * choose(4, 2)^2 * choose(11, 1) * choose(4, 1)
    ```

## 60

00
01
10
11

a)
    ```{r}
    3 / 4
    ```

b)
    ```{r}
    2 / 4
    ```

## 61

a)
    ```{r}
    choose(6, 3)
    ```

b)
    ```{r}
    6 * 5 * 3
    ```

## 62

## 63

## 64

a)
    ```{r}
    (6 / 21) * (6 / 21) * (6 / 21)
    ```

b)
    ```{r}
    (10 / 21) * (10 / 21) * (6 / 21)
    ```

## 65

```{r}
1 - ((4 / 6) * (3 / 5) * (2 / 4))
```

## 66

```{r}
6 * 5 * 4 * 3
```

## 67

Kombination

```{r}
choose(10, 3) + choose(5, 3)
```

## 68

```
p_a = 4 * p_b
p_b = 5 * p_c

p_a + p_b + p_c = 1
(4 * 5 * p_c) + 5 * p_c + p_c = 1
p_c = 1 / 26
p_b = 5 / 26
p_a = 20 / 26
```

## 69

```
P(p | s) = 0.85
p(s) = 0.75
P(p) = 0.7

P(s und p) = P(s) * P(p | s) = 0.75 * 0.85 = 0.6375

P(s | p) = P(s und p) / P(p) = 0.9107142857142857
```
## 70

```
P(korrekt | konsum) = 0.99
P(korrekt | kein-konsum) = 0.985
P(konsum) = 0.021
```

## 71

```
P(alt) = 0.6
P(jung) = 0.4

P(positiv | alt) = 0.3
P(positiv | jung) = 0.7

a)
    P(positiv)
```
