name: Build LaTeX Files to files repo
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4.1.2

      - name: Get directories to build
        run: |
          bash ./.github/scripts/get-directories-to-build.sh > directories.txt
          cat directories.txt

      - name: Convert directories to globs
        id: directories-to-globs
        run: |
          globs=$(cat directories.txt | bash ./.github/scripts/convert-directories-to-globs.sh)
          echo "GLOBS=$(printf -v var "%s;" "${globs[@]}")" >> "$GIHUB_OUTPUT"

      - name: Build LaTeX files
        if: ${{ steps.directories-to-globs.outputs.GLOBS }} != ''
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.directories-to-globs.outputs.GLOBS }}
          work_in_root_file_dir: true
          continue_on_error: true

      - name: Remove all non-PDF files
        run: |
          find . -type f ! -name '*.pdf' -delete

      - name: Push output to files repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.FILES_SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          user-email: root@fsoc.space
          destination-github-username: fs-c
          destination-repository-name: files
          target-branch: archive
          target-directory: jku/build
